version: '3'
services:
  db:
    image: "rettwalker/dbshackathon_db"
    container_name: dbshackathon_db
    environment:
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbshackathon
  server:
    build: .
    container_name: dbshackathon_server
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:securepassword@db/dbshackathon
    volumes:
    - .:/usr/src/app
    command: ["npm", "start"]
